apiVersion: apps/v1

kind: Deployment

metadata:

  name: goapp-deployment

  labels:

    app: goapp

spec:

  replicas: 1

  selector:

    matchLabels:

      app: goapp

  template:

    metadata:

      labels:

        app: goapp

    spec:

      containers:

      - name: goapp

        image: poonam3112/to-do-app-test

        ports:

        - containerPort: 8080

---

apiVersion: v1

kind: Service

metadata:

  name: goapp-service

spec:

  type: NodePort

  selector:

    app: goapp

  ports:

    - protocol: TCP

      port: 8080

      targetPort: 8080

      nodePort: 31000

  selector:

    deployment-label-key: goapp